config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'players#index'
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
		@players = Player.all
	end
	
	def new
		@player = Player.new
	end	

	def create
		@player = Player.new(player_params)
		if @player.save
		redirect_to root_path
	end
	end

	def show
		@player = Player.find_by(id: params[:id])
	end

	def edit
		@player = Player.find_by(id: params[:id])
	end
	
	def update
		@player = Player.find_by(id: params[:id])
		@player.update(player_params)
		if @player.save
			redirect_to player_path(@player.id)
		end	
	end

	def destroy
		@player = Player.find_by(id: params[:id])
		@player.destroy
		redirect_to root_path
	end

	private def player_params 
		params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
	end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player do |f| %>
<%= f.label :nickname %>
<%= f.text_field :nickname %><br/>
<%= f.label :rank %>
<%= f.text_field :rank %><br/>
<%= f.label :charisma %>
<%= f.text_field :charisma %><br/>
<%= f.label :wisdom %>
<%= f.text_field :wisdom %><br/>
<%= f.submit "Edit" %>
<% end %>

app/views/players/index.html.erb
<% if @players == [] %>
<p> There are no players yet <p/>
<% else %>
<% @players.each do |player| %>
<p>Player nickname is <%= player.nickname %><br/>
Player rank is <%= player.rank %><br/>
Player charisma is <%= player.charisma %><br/>
Player wisdom is <%= player.wisdom %><br/>
<%= link_to "Show more", player_path(player.id) %></p>
<% end %>
<% end %>
<%= link_to "Create new player", new_player_path %>

app/views/players/new.html.erb
<%= form_for @player do |f| %>
<%= f.label :nickname %>
<%= f.text_field :nickname %><br/>
<%= f.label :rank %>
<%= f.text_field :rank %><br/>
<%= f.label :charisma %>
<%= f.text_field :charisma %><br/>
<%= f.label :wisdom %>
<%= f.text_field :wisdom %><br/>
<%= f.submit "Create" %>
<% end %>

app/views/players/show.html.erb
<p> Player nickname is <%= @player.nickname %><br/>
Player rank is <%= @player.rank %><br/>
Player charisma is <%= @player.charisma %><br/>
Player wisdom is <%= @player.wisdom %><br/>
<%= link_to "Edit player", edit_player_path(@player.id) %><br/>
<%= link_to "Destroy player", player_path(@player.id), method: :delete, data: {confirm: "Are you sure?"} %></p>